version: "3.9"

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: corebank-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: corebank
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - corebank-net

  corebank-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: corebank-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/corebank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - corebank-net

volumes:
  pgdata:

networks:
  corebank-net:
